/*
 * This source file was generated by the Gradle 'init' task
 */
package flow.app;

public class MainApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new MainApp().getGreeting());
    }
}
